#!/bin/sh
MAKE="10"
KERNEL_DIR=$PWD
IMAGE_NAME=GaXus

# set kernel version
export TARGET_DEVICE=hammerhead
export BUILD_MOD=MSM
export BUILD_VERSION=V1.0.0

# set build user and host
export KBUILD_BUILD_VERSION="1"
export KBUILD_BUILD_USER="GaXus"
export KBUILD_BUILD_HOST="MSM"

###########################################################
# set android version
###########################################################
ANDROID_VERSION=KK

###########################################################
# don't edit this file
###########################################################
# release build
  BUILD_VERSION=`date +%Y%m%d`
  
    BUILD_VERSION=`date +%Y%m%d`"#$BUILD_NUMBER"
    export KBUILD_BUILD_VERSION="$BUILD_NUMBER"
export BUILD_LOCALVERSION="$TARGET_DEVICE-$ANDROID_VERSION-$BUILD_MOD-$BUILD_VERSION-$BUILD_TARGET"

# kernel vesion
KERNEL_VERSION=`grep '^VERSION = ' ./Makefile | cut -d' ' -f3`
KERNEL_PATCHLEVEL=`grep '^PATCHLEVEL = ' ./Makefile | cut -d' ' -f3`
KERNEL_SUBLEVEL=`grep '^SUBLEVEL = ' ./Makefile | cut -d' ' -f3`
export BUILD_KERNELVERSION="$KERNEL_VERSION.$KERNEL_PATCHLEVEL.$KERNEL_SUBLEVEL"
KERNEL_VER=`cat .version`
CWMIMAGE_NAME="GaXusKernel-$BUILD_VERSION$KERNEL_VER"

make_cwm_image()
{
    if [ -d tmp ]; then
        rm -rf tmp
    fi
    mkdir -p ./tmp/META-INF/com/google/android
    cp $IMAGE_NAME.img ./tmp/
    cp $KERNEL_DIR/release-tools/update-binary ./tmp/META-INF/com/google/android/
    sed -e "s/@VERSION/$BUILD_LOCALVERSION/g" $KERNEL_DIR/release-tools/$TARGET_DEVICE/updater-script-$IMAGE_NAME.sed > ./tmp/META-INF/com/google/android/updater-script
    cd tmp && zip -rq ../cwm.zip ./* && cd ../
    SIGNAPK_DIR=$KERNEL_DIR/release-tools/signapk
    java -jar $SIGNAPK_DIR/signapk.jar $SIGNAPK_DIR/testkey.x509.pem $SIGNAPK_DIR/testkey.pk8 cwm.zip $CWMIMAGE_NAME.zip
    rm cwm.zip
    rm -rf tmp
    echo "  $BIN_DIR/$CWMIMAGE_NAME.zip"
}


## Set compiler location
echo Setting compiler location...
export ARCH=arm
export CROSS_COMPILE=/home/gaxus/nexus5/toolchain2/bin/arm-linux-androideabi-

## Build Sultan kernel
make -j$MAKE ARCH=arm

# *.ko replace
echo ""
echo "=====> INSTALL KERNEL MODULES"
find -name '*.ko' -exec cp -av {} /home/gaxus/nexus5/ramdisk/lib/modules/ \;

## Compress ramdisk
/home/gaxus/nexus5/mkbootfs /home/gaxus/nexus5/ramdisk/ | gzip > ramdisk.gz

## Merge dt.img and initrd.img with zImage to create final boot.img
/home/gaxus/nexus5/mkbootimg --kernel arch/arm/boot/zImage-dtb --cmdline 'console=ttyHSL0,115200,n8 androidboot.hardware=hammerhead user_debug=31 msm_watchdog_v2.enable=1' --base 0x00000000 --pagesize 2048 --ramdisk_offset 0x02900000 --tags_offset 0x02700000 --ramdisk ramdisk.gz --output GaXus.img

##boot.img Copy
echo ""
echo "=====>GaXus Copy sultan.img"
cp GaXus.img ../

# create cwm image
echo ""
echo "=====>make cwm_image"
make_cwm_image

cd $KERNEL_DIR

echo ""
echo "====================================================================="
echo "    BUILD COMPLETED"
echo "====================================================================="
exit 0
